# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 没时间解释了，要写不完了
description: (ง •̀_•́)ง
baseurl: "" # the subpath of your site, e.g. /blog
github_username: 16S003001

# Build settings
markdown: kramdown
